const translations = {
    en: {
        profileDesc: "a 3D Generalist, passionate about bringing characters and environments to life. B3D, UE5, SP, Adobe.",
        backBtn: "Back",
        signature: "Designed by KuniDev",
        mail: "MAIL",
        artstation: "ARTSTATION",
        devlog: "DEVLOG",
        copied: "COPIED!",
        gallery1: { para1: "Video game developed in 3 days for WomenGameJam2025.", para2: "I led a team of 3 women to complete the game as quickly as possible. I wrote code, modeled, rigged, and animated." },
        gallery2: "Fan Art of Yunara.",
        gallery3: "A chibi fighter, inspired by a concept.",
        gallery4: "A cybergirl inspired by various concepts.",
        gallery5: "A stylized cyborg inspired by DeepChat, a YouTube video character.",
        gallery6: "Raze chibi, inspired by Valorant stickers.",
        gallery7: "A rusty robot for the Pwnisher 'Chasm Call' challenge.",
        gallery8: "A small project I developed when starting with 3D.",
        gallery9: "An adorable kitten for a mobile game.",
        gallery10: "Just a character I created with whatever came to mind."
    },
    zh: {
        profileDesc: "一个3D综合艺术家，热衷于赋予角色和环境生命。B3D, UE5, SP, Adobe。",
        backBtn: "返回",
        signature: "由KuniDev设计",
        mail: "邮件",
        artstation: "艺术站",
        devlog: "开发日志",
        copied: "已复制！",
        gallery1: { para1: "为WomenGameJam2025三天内开发的视频游戏。", para2: "我带领一个由3名女性组成的团队，尽快完成游戏。我编写代码、建模、绑定和动画。" },
        gallery2: "Yunara的粉丝艺术。",
        gallery3: "一个受概念启发的奇比战士。",
        gallery4: "一个受多种概念启发的赛博女孩。",
        gallery5: "一个受YouTube视频角色DeepChat启发的风格化赛博人。",
        gallery6: "Raze奇比，受Valorant贴纸启发。",
        gallery7: "为Pwnisher 'Chasm Call'挑战制作的生锈机器人。",
        gallery8: "我刚开始学习3D时开发的一个小项目。",
        gallery9: "一个适合手机游戏的可爱小猫。",
        gallery10: "只是一个凭空想象创建的角色。"
    },
    hi: {
        profileDesc: "एक 3D सामान्यवादी, जो पात्रों और पर्यावरणों को जीवन देने के लिए उत्साहित है। B3D, UE5, SP, Adobe।",
        backBtn: "वापस",
        signature: "KuniDev द्वारा डिज़ाइन किया गया",
        mail: "मेल",
        artstation: "आर्टस्टेशन",
        devlog: "डेवलॉग",
        copied: "कॉपी हो गया!",
        gallery1: { para1: "WomenGameJam2025 के लिए 3 दिनों में विकसित वीडियो गेम।", para2: "मैंने 3 महिलाओं की एक टीम का नेतृत्व किया ताकि खेल को जितनी जल्दी हो सके पूरा किया जा सके। मैंने कोड लिखा, मॉडलिंग की, रिगिंग की और एनिमेटेड किया।" },
        gallery2: "Yunara का प्रशंसक कला।",
        gallery3: "एक चिबी योद्धा, एक अवधारणा से प्रेरित।",
        gallery4: "विभिन्न अवधारणाओं से प्रेरित एक साइबरगर्ल।",
        gallery5: "एक स्टाइलिज्ड साइबोर्ग, YouTube वीडियो चरित्र DeepChat से प्रेरित।",
        gallery6: "Raze चिबी, Valorant स्टिकर से प्रेरित।",
        gallery7: "Pwnisher 'Chasm Call' चुनौती के लिए एक जंग लगी रोबोट।",
        gallery8: "3D शुरू करने पर विकसित एक छोटा प्रोजेक्ट।",
        gallery9: "एक मोबाइल गेम के लिए प्यारा बिल्ली का बच्चा।",
        gallery10: "बस एक चरित्र जो मैंने जो मन में आया उससे बनाया।"
    },
    es: {
        profileDesc: "Generalista 3D, apasionado por dar vida a personajes y ambientes. B3D, UE5, SP, Adobe.",
        backBtn: "Volver",
        signature: "Diseñado por KuniDev",
        mail: "MAIL",
        artstation: "ARTSTATION",
        devlog: "DEVLOG",
        copied: "¡COPIADO!",
        gallery1: { para1: "Videojuego desarrollado en 3 días para la WomenGameJam2025.", para2: "Lideré un equipo con 3 mujeres para que juntos completemos el juego lo más rápido posible. Escribí código, modelé, rigguié y animé." },
        gallery2: "Fan Art de Yunara.",
        gallery3: "Un luchador chibi, inspirado en un concept.",
        gallery4: "Una cybergirl inspirada de varios concepts.",
        gallery5: "Un cyborg styilized inspirado en DeepChat un personaje de un video de Youtube.",
        gallery6: "Raze chibi, inspirada de los stickers de Valorant.",
        gallery7: "Un robot rusty para el desafío de Pwnisher 'Chasm Call'.",
        gallery8: "Un pequeño proyecto que desarrollé cuando empezaba con el 3D. Elaborado en ZBrush y renderizado en Keyshot.",
        gallery9: "Un gatito adorable para un videojuego de celular.",
        gallery10: "Solo un personaje que cree con lo que se me ocurría en el momento."
    },
    ar: {
        profileDesc: "محترف ثلاثي الأبعاد، متحمس لإحياء الشخصيات والبيئات. B3D, UE5, SP, Adobe.",
        backBtn: "رجوع",
        signature: "تم التصميم بواسطة KuniDev",
        mail: "بريد",
        artstation: "محطة الفن",
        devlog: "سجل التطوير",
        copied: "تم النسخ!",
        gallery1: { para1: "لعبة فيديو طورت في 3 أيام لمسابقة WomenGameJam2025.", para2: "قادة فريق مكون من 3 نساء لإكمال اللعبة بأسرع وقت ممكن. كتبت الكود، نمذجت، ربطت، وأنمت." },
        gallery2: "فن المعجبين لـ Yunara.",
        gallery3: "محارب شيبي، مستوحى من مفهوم.",
        gallery4: "فتاة سايبر مستوحاة من مفاهيم مختلفة.",
        gallery5: "سايبورغ مستوحى من DeepChat، شخصية من فيديو يوتيوب.",
        gallery6: "Raze chibi، مستوحاة من ملصقات Valorant.",
        gallery7: "روبوت صدئ لتحدي Pwnisher 'Chasm Call'.",
        gallery8: "مشروع صغير طورت عندما بدأت مع الـ 3D.",
        gallery9: "قطة لطيفة للعبة موبايل.",
        gallery10: "فقط شخصية خلقتها بما كان يخطر ببالي في اللحظة."
    }
};
